from typing import Dict, Any, List
from langchain_core.messages import HumanMessage
import json
from typing import Optional
from langgraph.graph import MessagesState
from langgraph.types import Command
from typing import Literal, Optional, List, Dict, Any, Type
from state_message import State


def sum_token_usage(messages) -> Dict[str, int]:
    """
    Sum input/output token counts from a list of LangChain messages.
    Checks usage_metadata first, then response_metadata["token_usage"] as fallback.
    Safe to call with HumanMessages (which carry no usage) — they contribute 0.
    """
    input_tokens = 0
    output_tokens = 0
    for msg in messages:
        if hasattr(msg, "usage_metadata") and msg.usage_metadata:
            input_tokens += msg.usage_metadata.get("input_tokens", 0)
            output_tokens += msg.usage_metadata.get("output_tokens", 0)
        elif hasattr(msg, "response_metadata") and "token_usage" in (
            msg.response_metadata or {}
        ):
            usage = msg.response_metadata["token_usage"]
            input_tokens += usage.get("prompt_tokens", 0)
            output_tokens += usage.get("completion_tokens", 0)
    return {"input_tokens": input_tokens, "output_tokens": output_tokens}


MAX_REPLANS = 2


def get_agent_descriptions() -> Dict[str, Dict[str, Any]]:
    """
    Return structured agent descriptions with capabilities and guidelines.
    Edit this function to change how the planner/executor reason about agents.
    """
    return {
        "cosmos_order": {
            "name": "Cosmos Order Data",
            "capability": """
            Query order demand data that was submitted to the optimizer.
            Contains the original routing request, orders, delivery locations,
            quantities, weights, time windows, and equipment available before optimization.
        """,
            "use_when": """
            Use when the user is asking about:
            - Orders sent to the optimizer
            - Customer demand
            - Delivery locations
            - Quantities, weights, volumes, pallets
            - Order counts
            - Pickup and delivery information
            - Available equipment before planning
            - Demand trends over time
            This database represents optimizer INPUT data.
        """,
            "limitations": """
            Cannot create, modify, or delete data in the database.
            Cannot retrieve raw record-level data unless required to answer the user's request.
            Must minimize data retrieval and access only information necessary to complete the task.
        """,
        },
        "cosmos_route": {
            "name": "Cosmos Route Data",
            "capability": """
            Query route plans generated by the optimizer.
            Contains optimized routes, vehicle assignments, route utilization,
            distances, service times, and delivery sequencing.
        """,
            "use_when": """
            Use when the user is asking about:
            - Planned routes
            - Vehicle utilization
            - Route distance
            - Route duration
            - Route count
            - Stop sequencing
            - Vehicle assignments
            - Delivery performance
            This database represents optimizer OUTPUT data.
        """,
            "limitations": """
            - Cannot create, modify, or delete data in the database.
            - Cannot retrieve raw record-level data unless required to answer the user's request.
            - Must minimize data retrieval and access only information necessary to complete the task.
        """,
        },
        "synthesizer": {
            "name": "Synthesizer",
            "capability": "Write comprehensive prose summaries of findings",
            "use_when": "Final step when no visualization is requested - combines all previous research",
            "limitations": """
            - "Requires research data from previous steps"
            - Do not include file paths, temporary locations, internal processing details, or intermediate steps
        """,
            "output_format": "Coherent written summary incorporating all findings",
            "position_requirement": "Should be used as final step when no chart is needed",
        },
    }


def _get_enabled_agents(state: State | None = None) -> List[str]:
    """Return enabled agents; if absent, use baseline/default.

    Supports both dict-style and attribute-style state objects.
    """
    baseline = [
        "cosmos_order",
        "cosmos_route",
        "synthesizer",
    ]
    if not state:
        return baseline
    val = (
        state.get("enabled_agents")
        if hasattr(state, "get")
        else getattr(state, "enabled_agents", None)
    )

    if isinstance(val, list) and val:
        allowed = {
            "cosmos_order",
            "cosmos_route",
            "synthesizer",
        }
        filtered = [a for a in val if a in allowed]
        return filtered
    return baseline


def format_agent_list_for_planning(state: State | None = None) -> str:
    """
    Format agent descriptions for the planning prompt.
    """
    descriptions = get_agent_descriptions()
    enabled_list = _get_enabled_agents(state)
    agent_list = []

    for agent_key, details in descriptions.items():
        if agent_key not in enabled_list:
            continue
        agent_list.append(f"  • `{agent_key}` – {details['capability']}")

    return "\n".join(agent_list)


def format_agent_guidelines_for_planning(state: State | None = None) -> str:
    """
    Format agent usage guidelines for the planning prompt.
    """
    descriptions = get_agent_descriptions()
    enabled = set(_get_enabled_agents(state))
    guidelines = []

    # cosmos data
    if "cosmos_order" in enabled:
        guidelines.append(
            f"- Use `cosmos_order` when {descriptions['cosmos_order']['use_when'].lower()}."
        )
    if "cosmos_route" in enabled:
        guidelines.append(
            f"- Use `cosmos_route` when {descriptions['cosmos_route']['use_when'].lower()}."
        )
    if "synthesizer" in enabled:
        synth_desc = descriptions["synthesizer"]
        guidelines.append(
            f"  – Otherwise use `synthesizer` as {synth_desc['position_requirement'].lower()}, and be sure to include all of the data from the previous steps."
        )
    return "\n".join(guidelines)


def format_agent_guidelines_for_executor(state: State | None = None) -> str:
    """
    Format agent usage guidelines for the executor prompt.
    """
    descriptions = get_agent_descriptions()
    enabled = _get_enabled_agents(state)
    guidelines = []

    if "cosmos_order" in enabled:
        cosmos_order_desc = descriptions["cosmos_order"]
        guidelines.append(
            f"- Use `\"cosmos_order\"` when {cosmos_order_desc['use_when'].lower()}."
        )

    if "cosmos_route" in enabled:
        cosmos_route_desc = descriptions["cosmos_route"]
        guidelines.append(
            f"- Use `\"cosmos_route\"` when {cosmos_route_desc['use_when'].lower()}."
        )

    return "\n".join(guidelines)


def _build_conversation_context(state) -> str:
    """Build a compact conversation context block for the planner."""
    WINDOW_K = 3          # turns to keep in the active window
    parts = []

    running_summary = state.get("running_summary")
    if running_summary:
        parts.append(f"[Summary of prior conversation]\n{running_summary}")

    chat_history = state.get("chat_history") or []
    # Only last WINDOW_K turns
    window = chat_history[-(WINDOW_K * 2):]
    if window:
        turns_text = "\n".join(
            f"  {t['role'].upper()}: {t['content']}" for t in window
        )
        parts.append(f"[Recent conversation]\n{turns_text}")

    long_term = state.get("long_term_memories") or []
    if long_term:
        facts_text = "\n".join(f"  - {f}" for f in long_term)
        parts.append(f"[User preferences / long-term memory]\n{facts_text}")

    return "\n\n".join(parts)


def plan_prompt(state: State) -> HumanMessage:
    """
    Build the prompt that instructs the LLM to return a high‑level plan.
    """
    replan_flag = state.get("replan_flag", False)
    user_query = state.get("user_query", state["messages"][0].content)
    prior_plan = state.get("plan") or {}
    replan_reason = state.get("last_reason", "")

    # Get agent descriptions dynamically

    agent_list = format_agent_list_for_planning(state)
    agent_guidelines = format_agent_guidelines_for_planning(state)

    enabled_list = _get_enabled_agents(state)

    # Build planner agent enum based on enabled agents
    enabled_for_planner = [
        a for a in enabled_list if a in ("cosmos_order", "cosmos_route", "synthesizer")
    ]
    planner_agent_enum = (
        " | ".join(enabled_for_planner) or "synthesizer | cosmos_order | cosmos_route"
    )

    prompt = f"""
        You are the **Planner** in a multi‑agent system.  Break the user's request into a sequence of numbered steps (1, 2, 3, …).
        **There is no hard limit on step count** as long as the plan is concise and each step has a clear goal.
        You may decompose the user's query into sub-queries, each of which is a separate step.
        Break the query into the smallest possible sub-queries so that each sub-query is answerable with a single data source.
        For example, if the user's query is "What were the key action items in the last quarter, and what was a recent news story for each of them?",
        you may break it into steps:
        1. Fetch the key action items in the last quarter.
        2. Fetch a recent news story for the first action item.
        3. Fetch a recent news story for the second action item.
        4. Fetch a recent news story for the last action item
        If you need to use the agent to query data, do not retrieve raw record-level data unless it is required to answer the user's request,
        must minimize data retrieval and access only the information necessary to complete the task
        Here is a list of available agents you can call upon to execute the tasks in your plan. You may call only one agent per step.
        {agent_list}
        Return ONLY valid JSON format (no markdown, no explanations, no texts) in this form:
        {{
        "1": {{
            "agent": "{planner_agent_enum}",
            "action": "string",
        }},
        "2": {{ ... }},
        "3": {{ ... }}
        }}
        Guidelines:
        {agent_guidelines}
        """

    if replan_flag:
        prompt += f"""
        The current plan needs revision because: {replan_reason}

        Current plan:
        {json.dumps(prior_plan, indent=2)}

        When replanning:
        - Focus on UNBLOCKING the workflow rather than perfecting it.
        - Only modify steps that are truly preventing progress.
        - Prefer simpler, more achievable alternatives over complex rewrites.
        """

    else:
        prompt += "\nGenerate a new plan from scratch."
    conv_context = _build_conversation_context(state)
    if conv_context:
        prompt_content = f"Conversation context:\n{conv_context}\n\n---\n\n{prompt}"
    else:
        prompt_content = prompt
    prompt_content += f'\nUser query: "{user_query}"'
    return HumanMessage(content=prompt_content)


def executor_prompt(state: State) -> HumanMessage:
    """
    Build the single‑turn JSON prompt that drives the executor LLM.
    """
    step = int(state.get("current_step", 0))
    latest_plan: Dict[str, Any] = state.get("plan") or {}
    plan_block: Dict[str, Any] = latest_plan.get(str(step), {})
    max_replans = MAX_REPLANS
    attempts = (state.get("replan_attempts", {}) or {}).get(step, 0)

    # Get agent guidelines dynamically
    executor_guidelines = format_agent_guidelines_for_executor(state)

    messages_tail = (state.get("messages") or [])[-4:]

    executor_prompt = f"""
        You are the **executor** in a multi‑agent system with these agents:
        `{ '`, `'.join(sorted(set([a for a in _get_enabled_agents(state) if a in ['cosmos_order', 'cosmos_route', 'synthesizer']] + ['planner']))) }`.

        **Tasks**
        1. Decide if the current plan needs revision.  → `"replan_flag": true|false`
        2. Decide which agent to run next.             → `"goto": "<agent_name>"`
        3. Give one‑sentence justification.            → `"reason": "<text>"`
        4. Write the exact question that the chosen agent should answer
                                                    → "query": "<text>"

        **Guidelines**
        {executor_guidelines}
        - After **{MAX_REPLANS}** failed replans for the same step, move on.
        - If you *just replanned* (replan_flag is true) let the assigned agent try before
        requesting another replan.

        Respond **only** with valid JSON (no additional text):

        {{
        "replan": <true|false>,
        "goto": "<{ '|'.join([a for a in _get_enabled_agents(state) if a in ['cosmos_order', 'cosmos_route', 'synthesizer']] + ['planner']) }>",
        "reason": "<1 sentence>",
        "query": "<text>"
        }}

        **PRIORITIZE FORWARD PROGRESS:** Only replan if the current step is completely blocked.
        1. If any reasonable data was obtained that addresses the step's core goal, set `"replan": false` and proceed.
        2. Set `"replan": true` **only if** ALL of these conditions are met:
        • The step has produced zero useful information
        • The missing information cannot be approximated or obtained by remaining steps
        • `attempts < {max_replans}`
        3. When `attempts == {max_replans}`, always move forward (`"replan": false`).

        ### Decide `"goto"`
        - If `"replan": true` → `"goto": "planner"`.
        - If current step has made reasonable progress → move to next step's agent.

        ### Build `"query"`
        Write a clear, standalone instruction for the chosen agent.

        Ensure that the query uses consistent language as the user's query.

        Context you can rely on
        - User query ..............: {state.get("user_query")}
        - Current step index ......: {step}
        - Current plan step .......: {plan_block}
        - Just‑replanned flag .....: {state.get("replan_flag")}
        - Previous messages .......: {messages_tail}

        Respond **only** with JSON, no extra text.
        """

    return HumanMessage(content=executor_prompt)


def agent_system_prompt(suffix: str) -> str:
    return (
        "You are a helpful AI assistant, collaborating with other assistants."
        " Use the provided tools to progress towards answering the question."
        " If you are unable to fully answer, that's OK, another assistant with different tools "
        " will help where you left off. Execute what you can to make progress."
        # " If you or any of the other assistants have the final answer or deliverable,"
        # " prefix your response with FINAL ANSWER so the team knows to stop."
        f"\n{suffix}"
    )
